### ISSUE TITLE
some suggestions 

### ISSUE THREAD

**Issue by peow** [RobertHoueland/enchantments-plus#10]
some suggestions and bugs I found:

Life Steal has been behaving strangely, when I attack with the sword without waiting for its cooldown to recharge, I still get a lot of life back, even though I do very little damage, I believe it's bugged

It would be interesting if the Blaze Walker turned the affected obsidian back into lava after a while

Dual Leap is such a great enchantment, and I thought of an improvement for it, currently it is possible to use it to negate any fall damage, you just need to make the second jump just before reaching the ground, it would be interesting if it was configured a time limit to make the second jump to avoid this. something like 1 and a half seconds, if you try to make the second jump after this time has passed, you won't be able to

Sniper is very strong, I tested it on a bow without the Power enchantment and it is capable of taking 30 life from an Iron Golem at a distance of ~22 blocks. with Power 5 it takes more than 30 life, I believe it should be nerfed

These are my suggestions, great mod

**Comment by RobertHoueland** [comment]
Thank you for the comment! I appreciate the feedback and suggestions.

For Life Steal, I have had some odd bugs with it in the past. I'm making some changes to how it works that I believe will fix the current issues. Previously, it would heal you a fixed amount, no matter the target's health. This would mean you could spam attack and heal a lot. In the next release, it will instead heal you a portion of the target's health. This means if your life steal activates on a full health mob, you'll heal a lot. But a mob with low health will heal you less, which feels more balanced. Though I also realize that this means a weaker sword like a wooden sword could theoretically heal you more than a strong diamond sword, because if you're doing less damage you have more chances for life steal to activate. It seems difficult for the enchantment to access how much damage you're dealing, or else I would change the calculation to work with that value. I'll keep looking into it.

For Blaze Walker, I would like to keep it working how it is, as it's a bit unique compared to Frost Walker, and it would also make sense for obsidian to be permanent. 

For Dual Leap, I actually had never noticed that you could negate fall damage. After thinking about changing it, I like the idea that there's a side effect where you can stop fall damage if you are careful enough and precisely time your jump. *It's a feature, not a bug!* I might reconsider this in the future.

For Sniper, I will be adding a maximum damage amount to limit how you can one shot powerful mobs. I'll be keeping the damage calculation the same though, as the enchantment would be pretty weak if it did less damage. 

As for the Shiny Horses mod, I hadn't previously heard of this mod or used it, but I looked into it. For Lunar Sight, Hiker, Excavator, and Moon Walker, these enchantments all previously applied to Players, but I changed that so that they now apply to any Living Entity with the enchantment. The first 3 enchantments don't really apply to horses, but now Moon Walker will work with horses with the mod. As for Dual Leap, it's tricky to make it work with a non-player, so I probably won't be implementing that one with other living entities. I'm not entirely sure how the Shiny Horses mod works as it isn't open source as far as I can tell, so I don't know how to block Dual Leap from being enchanted. 

Be prepared for the changes in the next release!

**Comment by RobertHoueland** [comment]
[Done](https://github.com/RobertHoueland/enchantments-plus/releases/tag/1.2.0%2B1.20.1)
